config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  devise_scope :user do
    get '/sign_out', to: 'users/sessions#destroy'
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resources :likes, only: [:create]
    end
  end
   root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  has_many :comments, class_name: 'Comment'
  has_many :likes, class_name: 'Like'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def update_post_counter
    user.increment!(:posts_counter)
  end

  def most_recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  def short_text
    text.truncate(75)
  end

  def liked?(user)
    likes.where(user_id: user.id).any?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, class_name: 'Post', foreign_key: 'user_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id'
  has_many :likes, class_name: 'Like', foreign_key: 'user_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = 'Comment created!'
    else
      flash[:error] = 'Comment not created!'
    end
    redirect_to user_post_path(current_user, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])

    return if @post.liked?(current_user)

    @like = Like.new(user_id: current_user.id, post_id: @post.id)

    if @like.save
      flash[:success] = 'Liked!'
    else
      flash[:error] = 'ERROR! Not liked!'
    end
    redirect_to user_post_path(current_user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created!'
      redirect_to user_post_path(@user, @post)
    else
      flash[:error] = 'Post not created!'
      redirect_to "/users/#{@user.id}/posts/new"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if notice != nil %>
    <div class="alert success">
      <%= notice %>
    </div>
    <% end %>

    <% if alert != nil %>
    <div class="alert error">
      <%= alert %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'users/user' %>


<div class="user-posts">
  <% @user.posts.each do |post| %>
  <div class="user-bio black-border">
    <%= link_to post.title, user_post_path(user_id: @user.id, id: post.id), class: 'section-title' %>
    <p><%= post.short_text %></p>
    <p class="post-counters">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %> </p>
  </div>

  <ul class="post-comments black-border">
    <% post.most_recent_comments.includes([:user]).each do |comment| %>
    <li class="comment"><%= comment.user.name %>: <%= comment.text %></li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/posts/new.html.erb
<% flash.each do |type, msg| %>
<%= content_tag :div, msg, class: "#{type} alert" %>
<% end %>
<div class="new-post-container">
<h2 class="new-post-label">Create a new post:</h2>
<%= form_with url: "/users/#{@user.id}/posts", scope: :post, class: 'new-post-form' do |f| %>
      <%= f.text_field :title, placeholder: 'Title', class: 'new-post-title' %>
      <%= f.text_area :text, placeholder: 'Write your post here', class: 'new-post-text' %>
      <%= f.submit "Submit", class: 'new-post-btn' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<% flash.each do |type, msg| %>
<%= content_tag :div, msg, class: "#{type} alert" %>
<% end %>
<div class="post black-border">
  <div class="post-detailed">
    <h3> <%= @post.title %> by <%= @user.name %></h3>
    <p>Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>
  </div>

  <p><%= @post.text %></p>
    <%= form_with url: "#{@post.id}/likes", method: :post do |f| %>
      <%= f.submit "Like", class: 'like-btn' %>
    <% end %>
<div>
  <%= form_with url: "#{@post.id}/comments", scope: :comment, method: :post, class: 'comment-form' do |f| %>
    <%= f.text_area :text, placeholder: 'Write a comment...', required: true, class: 'comment-txt' %>
    <%= f.submit "Add comment", class: 'comment-btn' %> 
  <% end %> 
</div>
</div>
<ul class="post-comments black-border">
  <% @post.comments.includes([:user]).each do |comment| %>
    <li class="comment"><%= comment.user.name %>: <%= comment.text %></li>
  <% end %>
</ul>

app/views/users/_user.html.erb
<div class='user'>
  <img class="user-image black-border" src='<%= @user.photo %>' alt='user-photo'>
  <div class="user-data black-border">
    <%= link_to @user.name, user_path(id: @user.id), class: 'user-index-name' %>
    <p class="user-index-posts">Posts: <%= @user.posts_counter || 0 %></p>
  </div>
</div>
<div class="post-btn-container">
<%= link_to 'New Post', new_user_post_path(user_id: @user.id), class: 'new-post-btn' %>
</div>

app/views/users/index.html.erb
  <% @users.each do |user| %>
    <div class='user'>
      <img class="user-image black-border" src='<%= user.photo %>' alt='user-photo'>
      <div class="user-data black-border">
      <p>
        <%= link_to user.name, user_path(id: user.id), class: 'user-index-name' %>
      </p>
      <p class="user-index-posts">Posts: <%= user.posts_counter || 0 %></p>
      </div>
    </div>
  <% end %>

app/views/users/show.html.erb
<%= render 'users/user' %>

<div class='user-bio black-border'>
  <p>Bio: <%= @user.bio %></p>
</div>

<div class="user-posts">
  <% @user.most_recent_posts.each do |post| %>
  <div class="user-bio black-border">
    <%= link_to post.title, user_post_path(user_id: @user.id, id: post.id), class: 'section-title' %>
    <p><%= post.short_text %></p>
    <p class="post-counters">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></p>
  </div>
  <% end %>
</div>

<%= link_to 'See all posts', user_posts_path(user_id: @user.id), class: 'btn-container posts-btn black-border' %>